### ISSUE TITLE
Request: Order lectures in numerical order.

### ISSUE THREAD

**Issue by miguelraz** [stevengj/1806#6]
Currently, the lectures are organized by alphabetical order. 
Would it be possible to organize them sequentially, in the order they were given?
It would help to know the pace and structure of the course a bit better.

**Comment by stevengj** [comment]
Look at the links to the Fall 17 and Spring 18 summaries at https://github.com/stevengj/1806/blob/master/summaries.md, which link to the lectures in order.

**Comment by stevengj** [comment]
I'd prefer not, because e.g. if I insert a new lecture or split one lecture into two then I would need to rename all of the other files.

**Comment by dlutleixin** [comment]
> https://github.com/stevengj/1806/blob/master/summaries.md

page not found

**Comment by stevengj** [comment]
In most of the more recent semesters the lecture summaries are in the README.md
